### ISSUE TITLE
Unable to find class

### ISSUE THREAD

**Issue by pitchblack408** [kriegaex/JarClassLoader#1]
Hello, I found this page because I am trying to figure out how to use maven to create a single runable jar.  The problem I have with other maven plugins is that I am using bouncy castle.  So, I see that you wrote this to fix that problem.  Really cool.  I am learning maven still.  So, I may not be using it right.  When I compile and run my code with eclipse all is well. But after trying you build set up in maven I am having issues. It appears that it is not finding some dependencies.  I have a jar that I made called nsws-2017-1.jar which was installed into my local repo and it is included as a dependency in my pom.  This class that it is complaining about is in that jar.  I  ran mvn clean package to create the build.
What do you suppose is going on?

$ java -jar goldfish-netsuite-customer-1.8.2.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/netsuite/webservices/platform_2017_1/NetSuiteServiceLocator
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.netsuite.webservices.platform_2017_1.NetSuiteServiceLocator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by kriegaex** [comment]
I can only speculate without seeing your project, especially your POM. So if you could share it with me via GitHub or in another way, I could take a look.

**Comment by wwwAiru** [comment]
Hi i have a problem with bouncy castle provider in jar. i'm newbie in java and i have problem how implement your tutorial to my project. Can you help me add custom class loader to my project.  https://github.com/wwwAiru/web-push

**Comment by kriegaex** [comment]
4 years without feedback → closing the issue.
